### PR TITLE
new feature: optional prompt for envshell

### PR DESCRIPTION
**Pull request by slafs**
this sets a new env variable called `ENVDIR_PS1`
before running a new shell so for example in bash
it can be used to set a new shell prompt
(similar to virtualenv)

all you'd need to do is add a line similar to this
at the bottom of your .bashrc

```
PS1=${ENVDIR_PS1:-${PS1}}
```

so after running `envshell ./test/` you would get `[envdir:test]`
at the beginning of your prompt.

### CODE REVIEW

**Comment by judy2k** [comment]
I feel like this could do with a test to ensure the vars are set. @slafs would you be prepared to do that? Then I'll try to get this merged in.

**Comment by slafs** [comment]
Sure! Will try.

**Comment by blueyed** [comment]
@slafs 
Any update on this?

**Comment by slafs** [comment]
Done :). Although we probably need #45 fist.

**Comment by blueyed** [comment]
Thanks!

#45 is merged - please rebase on master.

**Comment by slafs** [comment]
Done. Looks like appveyor failed on py26 (not on mine test though).

**Comment by blueyed** [comment]
I would say by now that only `ENVSHELL_PATH` is required, because `ENVSHELL_NAME` can easily get derived from it in your shell (`${ENVSHELL_PATH##*/}`).

**Comment by slafs** [comment]
I wouldn't say "easily". That's some serious bash-fu right there. I can remove it, but I'd "vote" it to stay.

**Comment by blueyed** [comment]
> I wouldn't say "easily".

I can see that it's not obvious, but should be known / easy to find if you're into shell scripting.
What about `$(basename "$ENVSHELL_PATH")`?

We could also provide the code in the documentation.

**Comment by slafs** [comment]
Oh, right. I forgot that `basename` is also present in shell. I'm ok with this then.

**Comment by lwm** [comment]
Merrrgggeeeeeeeee :beers:

**Comment by blueyed** [comment]
@lwm 
`ENVSHELL_NAME` is still in the PR.

@slafs 
Do you want to remove it?
Does everybody agree that a single env var is enough?

I'm really undecided on this myself.

**Comment by slafs** [comment]
yes, I'll remove it.

**Pull request closed without merging**
